### ISSUE TITLE
Labelling the GitHub repository tickets

### ISSUE THREAD

**Issue by tapaswenipathak** [beeware/beeware.github.io#363]
Hi Maintainers!

I am thinking of contributing in different projects of the beeware org. I was seeing the tickets aren't labelled in any GitHub repository. If you can label the tickets, would help folks who would like contributing.

**Comment by freakboy3742** [comment]
Hi @tapaswenipathak!

We've done this with some tickets on some projects (e.g., https://github.com/beeware/toga/issues). However, while tickets are a good way to interact with an established project, BeeWare is sufficiently new that tickets aren't the best way for a new contributor to get involved with the project. 

Tickets are really good when there is a clearly defined bug to resolve. However, when we're still at the "implement major features" stage of development, tickets aren't necessarily the most efficient way to communicate what needs to be done. In order for tickets to be effective, we'd need to write up hundreds of tickets. This wouldn't lead to tickets that are good for first-time contributors, though - it would be describing prototype APIs for major feature developments, which generally isn't the best place for a first time contributor to join in.

Instead, we've written up [this document](https://beeware.org/contributing/how/first-time/) as a guide for how to get involved as a first time contributor, backed up by contribution guides in individual projects docuementation. If you've got suggestions for how to effectively direct people to that page, let us know!

(That said - we also need to do lots of gardening and weed-pulling on the tickets we have... there are lots of stale, out of date tickets, or unhelpful tickets in our various repositories...)

Closing this ticket on the basis that there isn't a clear "success" criteria for this activity - even if we did take your advice, it would be an "ongoing aspiration" activity, rather than something that would ever be "complete". However, if you've got other specific ideas on how to improve engagement of first-time contributors, let us know (either here, or on a new ticket)!

**Comment by tapaswenipathak** [comment]
Hey: thanks for writing, a lot of text/information, just an ack, I didn't properly read the text; I would be happy being useful. I have seen your work and I knew the projects you are involved with are great for folks who would like getting involved. Happy remaining day!

**Comment by tapaswenipathak** [comment]
On Mon, Sep 9, 2019 at 5:32 AM Russell Keith-Magee
<notifications@github.com> wrote:
>
> Hi @tapaswenipathak!
>
> We've done this with some tickets on some projects (e.g., https://github.com/beeware/toga/issues). However, while tickets are a good way to interact with an established project, BeeWare is sufficiently new that tickets aren't the best way for a new contributor to get involved with the project.
>
> Tickets are really good when there is a clearly defined bug to resolve. However, when we're still at the "implement major features" stage of development, tickets aren't necessarily the most efficient way to communicate what needs to be done. In order for tickets to be effective, we'd need to write up hundreds of tickets. This wouldn't lead to tickets that are good for first-time contributors, though - it would be describing prototype APIs for major feature developments, which generally isn't the best place for a first time contributor to join in.
>
> Instead, we've written up this document as a guide for how to get involved as a first time contributor, backed up by contribution guides in individual projects docuementation. If you've got suggestions for how to effectively direct people to that page, let us know!
>
> (That said - we also need to do lots of gardening and weed-pulling on the tickets we have... there are lots of stale, out of date tickets, or unhelpful tickets in our various repositories...)
>
> Closing this ticket on the basis that there isn't a clear "success" criteria for this activity - even if we did take your advice, it would be an "ongoing aspiration" activity, rather than something that would ever be "complete". However, if you've got other specific ideas on how to improve engagement of first-time contributors, let us know (either here, or on a new ticket)!

Hey: thanks for writing, a lot of text/information, just an ack, I
didn't properly read the text; I would be happy being useful. I have
seen your work and I knew the projects you are involved with are great
for folks who would like getting involved. Happy day!

>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni
